// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywoowmudcvpxhunvopsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3b293bXVkY3ZweGh1bnZvcHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Mzk4ODksImV4cCI6MjA3NDIxNTg4OX0.jH_6PnpF67IYATGfOXQlpPEN0r_QGS67b0b0EPBHnxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});